import Header from "../components/header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "ultimate profile website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className="snap-y snap-mandatory scroll-smooth overflow-y-scroll overflow-x-hidden scrollbar-thin scrollbar-track-gray-400/20 scrollbar-thumb-[#00C6CF]/80"
    >
      <body className="text-gray-300 bg-[rgb(36,36,36)]">
        <Header />
        {children}
      </body>
    </html>
  );
}
